version: '3.9'

services:
  conmebol_db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    networks:
      - conmebol_net
    deploy:  
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  conmebol:
    build: .
    environment:
      GUNICORN: false
    volumes:
      - .:/usr/app
    ports:
      - 80:80
    networks:
      - conmebol_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    depends_on:
      conmebol_db:
        condition: service_started

networks:
  conmebol_net:
    driver: bridge
    name: conmebol_net